Repository ihs-gwc/ihs-gwc-website, pull requests merged in 2020-12, with the labels that each got.

#94 New Subpage Files
  events/fieldTrip.html
  events/fundraiser.html
  events/guestSpeaker.html
Labels: documentation, enhancement

#95 Update events index to link to proper subpages
  events/index.html
Labels: bug

#96 Made separate menu and footer files
  about.html
  contact.html
  css/style.css
  curriculum.html
  events.html
  events/boograms.html
  events/fieldTrip.html
  events/fundraiser.html
  events/guestSpeaker.html
  events/index.html
  footer.html
  index.html
  js/main.js
  menu.html
  recaps.html
  semester1.html
  semester2.html
Labels: cleanup

#99 Event subpage names and cleanup
  events/boo-grams.html
  events/ftb-fundraiser.html
  events/guest-speakers.html
  events/index.html
  events/tech-museum.html
Labels: cleanup
